# Build the image from a pinned lockfile so two builds a month apart are the same image.
# requirements.lock is generated by `uv pip compile pyproject.toml -o requirements.lock`.
FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

WORKDIR /srv

# Dependencies first: this layer only rebuilds when the lockfile changes.
COPY requirements.lock ./
RUN pip install --no-cache-dir -r requirements.lock

COPY pyproject.toml ./
COPY app ./app
COPY data/sample_tickets.json data/demo_tickets.json data/gold.jsonl ./data/
RUN pip install --no-cache-dir --no-deps . && mkdir -p /srv/data

# Run as a non-root user; the audit DB lives on a writable volume.
RUN useradd --create-home --uid 10001 climb && chown -R climb:climb /srv
USER climb

ENV AUDIT_DB_PATH=/srv/data/audit.db PORT=8080
EXPOSE 8080
HEALTHCHECK --interval=15s --timeout=3s --start-period=10s \
  CMD python -c "import urllib.request,os;urllib.request.urlopen('http://127.0.0.1:%s/health'%os.environ.get('PORT','8080'))" || exit 1
CMD ["sh", "-c", "uvicorn app.main:app --host 0.0.0.0 --port ${PORT}"]
